version: "3.9"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d/
      - postgresdb:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gotest
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: gopassword

  jaeger:
    image: jaegertracing/all-in-one:1.28
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: gouser
      MONGO_INITDB_ROOT_PASSWORD: gopassword
      MONGO_DATA_DIR: ./database-data/mongodb
      MONGO_LOG_DIR: /dev/null
    ports:
      - "27017:27017"

volumes:
  postgres:
    name: postgresdb
  mongodb:
    name: mongodb