// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/domain/service/auth.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	entity "calendar.com/pkg/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthorization is a mock of Authorization interface.
type MockAuthorization struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationMockRecorder
}

// MockAuthorizationMockRecorder is the mock recorder for MockAuthorization.
type MockAuthorizationMockRecorder struct {
	mock *MockAuthorization
}

// NewMockAuthorization creates a new mock instance.
func NewMockAuthorization(ctrl *gomock.Controller) *MockAuthorization {
	mock := &MockAuthorization{ctrl: ctrl}
	mock.recorder = &MockAuthorizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorization) EXPECT() *MockAuthorizationMockRecorder {
	return m.recorder
}

// CheckCredentials mocks base method.
func (m *MockAuthorization) CheckCredentials(arg0 entity.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCredentials", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckCredentials indicates an expected call of CheckCredentials.
func (mr *MockAuthorizationMockRecorder) CheckCredentials(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCredentials", reflect.TypeOf((*MockAuthorization)(nil).CheckCredentials), arg0)
}

// GenerateToken mocks base method.
func (m *MockAuthorization) GenerateToken(login string) (*entity.AuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", login)
	ret0, _ := ret[0].(*entity.AuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthorizationMockRecorder) GenerateToken(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuthorization)(nil).GenerateToken), login)
}
